name: genome-loader
channels:
  - bioconda
  - conda-forge
dependencies:
  - bcftools
  - dask
  - joblib
  - natsort
  - numba
  - numpy
  - pyarrow
  - pybigwig
  - pysam
  - python>=3.8.*
  - tiledb::tiledbvcf-py
  - tqdm
  - xarray
  - zarr
platforms:
  - linux-64