name: genome-loader
channels:
  - bioconda
  - conda-forge
dependencies:
  - bcftools
  - dask
  - h5py
  - natsort
  - numba
  - numpy
  - pyarrow
  - pybigwig
  - pysam
  - python>=3.8.*
  - ray-core
  - tiledb::tiledbvcf-py
  - tqdm
  - xarray
  - zarr
  - pip:
    - tensorstore
platforms:
  - linux-64