name: genome-loader
channels:
  - bioconda
  - conda-forge
dependencies:
  - attrs
  # - cyvcf2 # optional
  - dask
  - joblib
  - natsort
  - numba
  - numpy
  - pandera
  # - pgenlib # optional
  - pyarrow
  - pybigwig
  - pysam
  - python>=3.8.*
  - ray-default
  # - tiledb::tiledbvcf-py # optional
  - xarray
  - zarr
platforms:
  - linux-64