name: genome-loader
channels:
  - bioconda
  - conda-forge
dependencies:
  - biconda::bcftools
  - bioconda::cyvcf2 # needed to read VCF with sgkit
  - dask
  - einops
  - h5py
  - natsort
  - numba
  - numcodecs
  - numpy
  - pandas
  - polars>=0.15.13
  - pyarrow
  - bioconda::pysam
  - python>=3.7.*
  - sgkit
  - tqdm
  - typer
  - xarray
  - zarr
  # preprocessing
  - biconda::gffutils
  # torch
  - pytorch::pytorch
  - pytorch::cpuonly
  - pytorch::torchvision
  - pytorch-lightning
  # dev dependencies
  - black
  - gh
  - git
  - icecream
  - isort
  - mypy
  - pip
  - pipreqs
  - pre-commit
  - pytest
  - pytest-cases
  - pytest-cov
  - jupyter
  - jupyterlab
  - pip:
    - tensorstore
platforms:
  - linux-64
  - osx-64
category: dev