name: genome-loader
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - bioconda::cyvcf2 # needed to read VCF with sgkit
  - dask
  - einops
  - h5py
  - numba
  - numpy
  - pandas
  - polars
  - pyarrow
  - bioconda::pysam
  - python>=3.7.*
  - sgkit
  - tqdm
  - typer
  - xarray
  - zarr
  # dev
  - black
  - conda-lock
  - git
  - icecream
  - isort
  - mypy
  - pipreqs
  - pre-commit
  - pytest
  - pytest-cases
  - pytest-cov
platforms:
  - linux-64
  - osx-64
category: dev