name: genome-loader
channels:
  - bioconda
  - conda-forge
dependencies:
  - biconda::bcftools
  - bioconda::cyvcf2 # needed to read VCF with sgkit
  - dask
  - einops
  - h5py
  - joblib
  - natsort
  - nest-asyncio
  - numba
  - numcodecs
  - numpy
  - pandas
  - pandera
  - pyarrow
  - bioconda::pysam
  - python>=3.7.*
  - sgkit
  - tqdm
  - typer
  - xarray
  - zarr
  - pip:
    - tensorstore
platforms:
  - linux-64
  - osx-64