name: genome-loader
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconda::cyvcf2 # needed to read VCF with sgkit
  - dask
  - einops
  - h5py
  - natsort
  - numba
  - numcodecs
  - numpy
  - pandas
  - polars>=0.15.13
  - pyarrow
  - bioconda::pysam
  - python>=3.7.*
  - sgkit
  - tqdm
  - typer
  - xarray
  - zarr
platforms:
  - linux-64
  - osx-64