name: genome-loader
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.7.*
  - numpy
  - pandas
  - polars
  - pyarrow
  - h5py
  - sgkit
  - bioconda::pysam
  - bioconda::cyvcf2 # needed to read VCF with sgkit
  - numba
  - dask
  - xarray
  - zarr
platforms:
  - linux-64
  - osx-64