[tool.isort]
profile = "black"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[tool.pytest.ini_options]
addopts = "-v"
filterwarnings = [
    'ignore:.*the `scipy\.stats\.stats` namespace is deprecated.*:DeprecationWarning'
]
markers = [
    "encode_spec",
    "encode_sequence",
    "encode_fasta",
    "exceptions",
    "validate_chroms",
    "encode_haps"
]